// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"time"
)

type KciCmnOrganization struct {
	ID               int32
	Relationship     sql.NullString
	Active           int8
	OrganizationType sql.NullString
	Name             sql.NullString
	LicDate          sql.NullTime
	TermDate         sql.NullTime
	Red              int8
	CreditRating     sql.NullString
	NfrcCode         sql.NullString
	Notes            sql.NullString
	GlobalNotes      sql.NullString
	BillingNotes     sql.NullString
	IncludeBox       int8
	PermittedEmails  sql.NullString
	LabelPrefs       sql.NullString
	TrackableId      sql.NullString
	Timestamp        time.Time
}

type KciKdbBillableitem struct {
	ID          int32
	VendorId    sql.NullInt32
	Item        string
	Description sql.NullString
	Year        sql.NullInt32
	Active      sql.NullInt16
	Amount      string
}

type KciKdbBilling struct {
	ID           int32
	Date         time.Time
	CustId       int32
	Invoicenum   sql.NullString
	TrackableRef string
	Total        string
	TrackableId  sql.NullString
}

type KciKdbBillitem struct {
	ID        int32
	BillingId int32
	ItemId    int32
	Quantity  int32
	Amount    string
}

type KciKdbIgcert struct {
	ID            int32
	CustId        sql.NullInt32
	Igcertid      sql.NullInt32
	Description   sql.NullString
	Configuraton  sql.NullString
	NfrcSpCode    sql.NullString
	Spacer        sql.NullString
	Desiccant     sql.NullString
	Cornerkey     sql.NullString
	Prisealtype   sql.NullString
	Secsealtype   sql.NullString
	Lowetype      sql.NullString
	Gas           int8
	Gasfillmethod sql.NullString
	Refstd        sql.NullString
	Testreportno  sql.NullString
	Lang          sql.NullString
	Certdate      sql.NullTime
	Revdate       sql.NullTime
	Rewitdate     sql.NullTime
	Expdate       sql.NullTime
	LabId         sql.NullInt32
	Labaddress    sql.NullInt32
	Labcontact    sql.NullInt32
	Notes         sql.NullString
	Billable      int8
	Billnotes     sql.NullString
	TrackableId   sql.NullString
	Extexpdate    sql.NullTime
	Timestamp     time.Time
}

type KciKdbIgset struct {
	ID                   int32
	IgCert               sql.NullInt32
	IgSetId              int32
	IgSetType            sql.NullString
	Buildcount           sql.NullInt32
	CertCycle            sql.NullInt32
	Description          sql.NullString
	Inspectorresponsible sql.NullString
	Isremotefab          sql.NullInt16
	Testreportno         sql.NullString
	Witnessed            int8
	ScheduledFabDate     sql.NullTime
	Configuraton         sql.NullString
	NfrcSpCode           sql.NullString
	Spacer               sql.NullString
	Desiccant            sql.NullString
	Cornerkey            sql.NullString
	Prisealtype          sql.NullString
	Secsealtype          sql.NullString
	Lowetype             sql.NullString
	InternalComp         sql.NullString
	Gas                  int8
	Gasfillmethod        sql.NullString
	Glazthickness        sql.NullString
	Spacthickness        sql.NullString
	Spacthickness2       sql.NullString
	Refstd               sql.NullString
	LabId                sql.NullInt32
	Labaddress           sql.NullInt32
	Labcontact           sql.NullInt32
	Viewlink             sql.NullString
	Editlink             sql.NullString
	Adminlink            sql.NullString
	Cogformentryid       sql.NullInt32
	TrackableId          sql.NullString
	Timestamp            time.Time
}

type KciKdbIgsetswithstatus struct {
	ID                   int32
	IgCert               sql.NullInt32
	IgSetId              int32
	IgSetType            sql.NullString
	Buildcount           sql.NullInt32
	CertCycle            sql.NullInt32
	Description          sql.NullString
	Inspectorresponsible sql.NullString
	Isremotefab          sql.NullInt16
	Testreportno         sql.NullString
	Witnessed            int8
	ScheduledFabDate     sql.NullTime
	Configuraton         sql.NullString
	NfrcSpCode           sql.NullString
	Spacer               sql.NullString
	Desiccant            sql.NullString
	Cornerkey            sql.NullString
	Prisealtype          sql.NullString
	Secsealtype          sql.NullString
	Lowetype             sql.NullString
	InternalComp         sql.NullString
	Gas                  int8
	Gasfillmethod        sql.NullString
	Glazthickness        sql.NullString
	Spacthickness        sql.NullString
	Spacthickness2       sql.NullString
	Refstd               sql.NullString
	LabId                sql.NullInt32
	Labaddress           sql.NullInt32
	Labcontact           sql.NullInt32
	Viewlink             sql.NullString
	Editlink             sql.NullString
	Adminlink            sql.NullString
	Cogformentryid       sql.NullInt32
	TrackableId          sql.NullString
	Timestamp            time.Time
	StatusCode           sql.NullInt32
	StatusType           sql.NullString
	StatusDate           sql.NullTime
	StatusNote           sql.NullString
	EnteredBy            sql.NullString
	AssignedTo           sql.NullInt32
	FlagOn               sql.NullTime
	Statusdesc           sql.NullString
	Daysuntilflag        sql.NullInt32
}

type KciKdbInvoiceaddonreport struct {
	LicprogramId        int32
	Type                sql.NullString
	AddOnName           sql.NullString
	AddOnListId         sql.NullString
	DiscountName        sql.NullString
	DiscountListId      sql.NullString
	Description         sql.NullString
	AddOnDesc           sql.NullString
	DiscountDesc        sql.NullString
	Count               sql.NullInt32
	Amount              sql.NullString
	Pct                 sql.NullString
	Price               sql.NullString
	PricePercent        sql.NullString
	DiscountRate        sql.NullString
	DiscountRatePercent sql.NullString
	Addonseq            sql.NullInt32
	Notes               sql.NullString
}

type KciKdbInvoiceservicereport struct {
	ID                int32
	LocationId        int32
	ProgramId         int32
	InvoiceMonth      sql.NullInt32
	PayorCustId       sql.NullInt32
	InvoiceDesc       sql.NullString
	InvoiceNotes      sql.NullString
	Name              sql.NullString
	ListId            sql.NullString
	Description       sql.NullString
	Price             sql.NullString
	PricePercent      sql.NullString
	InvoiceSeq        sql.NullInt32
	DefaultInvoiceSeq sql.NullInt32
}

type KciKdbStatus struct {
	ID           int32
	TrackableId  string
	StatusCode   int32
	StatusType   string
	StatusCurNum sql.NullInt32
	StatusDate   sql.NullTime
	StatusNote   sql.NullString
	EnteredBy    sql.NullString
	AssignedTo   sql.NullInt32
	FlagOn       sql.NullTime
	Timestamp    time.Time
}

type KciQbAppliedtotxnret struct {
	TxnId                         string
	Txntype                       sql.NullString
	Txndate                       sql.NullTime
	Refnumber                     sql.NullString
	Balanceremaining              sql.NullString
	Creditremaining               sql.NullString
	Creditremaininginhomecurrency sql.NullString
	Refundamountinhomecurrency    sql.NullString
	Amount                        sql.NullString
	Discountamount                sql.NullString
	DiscountaccountrefListid      sql.NullString
	DiscountaccountrefFullname    sql.NullString
	DiscountclassrefListid        sql.NullString
	DiscountclassrefFullname      sql.NullString
	ParentIdKey                   sql.NullString
	SeqNum                        sql.NullInt32
	UserData                      sql.NullString
	Lsdata                        sql.NullString
}

type KciQbCustomer struct {
	ListId                      string
	Timecreated                 sql.NullTime
	Timemodified                sql.NullTime
	Editsequence                sql.NullString
	Name                        sql.NullString
	Fullname                    sql.NullString
	Isactive                    sql.NullString
	Companyname                 sql.NullString
	Salutation                  sql.NullString
	Firstname                   sql.NullString
	Middlename                  sql.NullString
	Lastname                    sql.NullString
	Suffix                      sql.NullString
	Printas                     sql.NullString
	BilladdressAddr1            sql.NullString
	BilladdressAddr2            sql.NullString
	BilladdressAddr3            sql.NullString
	BilladdressAddr4            sql.NullString
	BilladdressAddr5            sql.NullString
	BilladdressCity             sql.NullString
	BilladdressState            sql.NullString
	BilladdressPostalcode       sql.NullString
	BilladdressCountry          sql.NullString
	BilladdressNote             sql.NullString
	ShipaddressAddr1            sql.NullString
	ShipaddressAddr2            sql.NullString
	ShipaddressAddr3            sql.NullString
	ShipaddressAddr4            sql.NullString
	ShipaddressAddr5            sql.NullString
	ShipaddressCity             sql.NullString
	ShipaddressState            sql.NullString
	ShipaddressPostalcode       sql.NullString
	ShipaddressCountry          sql.NullString
	ShipaddressNote             sql.NullString
	Phone                       sql.NullString
	Mobile                      sql.NullString
	Pager                       sql.NullString
	Altphone                    sql.NullString
	Fax                         sql.NullString
	Email                       sql.NullString
	Contact                     sql.NullString
	Altcontact                  sql.NullString
	CustomertyperefListid       sql.NullString
	CustomertyperefFullname     sql.NullString
	TermsrefListid              sql.NullString
	TermsrefFullname            sql.NullString
	SalesreprefListid           sql.NullString
	SalesreprefFullname         sql.NullString
	Balance                     sql.NullString
	Openbalancedate             sql.NullTime
	Totalbalance                sql.NullString
	Salestaxcountry             sql.NullString
	Resalenumber                sql.NullString
	Accountnumber               sql.NullString
	Creditlimit                 sql.NullString
	PfdpaymentmethodrefListid   sql.NullString
	PfdpaymentmethodrefFullname sql.NullString
	Notes                       sql.NullString
	ExternalGuid                sql.NullString
	Taxregistrationnumber       sql.NullString
	CurrencyrefListid           sql.NullString
	CurrencyrefFullname         sql.NullString
	Deliverymethod              sql.NullString
	Jobtitle                    sql.NullString
	Cc                          sql.NullString
	Preferreddeliverymethod     sql.NullString
	CustId                      sql.NullString
	UserData                    sql.NullString
	Operation                   sql.NullString
	Lsdata                      sql.NullString
}

type KciQbInvoice struct {
	TxnId                       string
	Timecreated                 sql.NullTime
	Timemodified                sql.NullTime
	Editsequence                sql.NullString
	Txnnumber                   sql.NullInt32
	CustomerRefListId           sql.NullString
	CustomerrefFullname         sql.NullString
	ClassrefListid              sql.NullString
	ClassrefFullname            sql.NullString
	AraccountrefListid          sql.NullString
	AraccountrefFullname        sql.NullString
	TemplaterefListid           sql.NullString
	TemplaterefFullname         sql.NullString
	Txndate                     sql.NullTime
	Refnumber                   sql.NullString
	BilladdressAddr1            sql.NullString
	BilladdressAddr2            sql.NullString
	BilladdressAddr3            sql.NullString
	BilladdressAddr4            sql.NullString
	BilladdressAddr5            sql.NullString
	BilladdressCity             sql.NullString
	BilladdressState            sql.NullString
	BilladdressPostalcode       sql.NullString
	BilladdressCountry          sql.NullString
	BilladdressNote             sql.NullString
	ShipaddressAddr1            sql.NullString
	ShipaddressAddr2            sql.NullString
	ShipaddressAddr3            sql.NullString
	ShipaddressAddr4            sql.NullString
	ShipaddressAddr5            sql.NullString
	ShipaddressCity             sql.NullString
	ShipaddressState            sql.NullString
	ShipaddressPostalcode       sql.NullString
	ShipaddressCountry          sql.NullString
	ShipaddressNote             sql.NullString
	Ispending                   sql.NullString
	Isfinancecharge             sql.NullString
	Ponumber                    sql.NullString
	TermsrefListid              sql.NullString
	TermsrefFullname            sql.NullString
	Duedate                     sql.NullTime
	SalesreprefListid           sql.NullString
	SalesreprefFullname         sql.NullString
	Fob                         sql.NullString
	Shipdate                    sql.NullTime
	ShipmethodrefListid         sql.NullString
	ShipmethodrefFullname       sql.NullString
	Subtotal                    sql.NullString
	ItemsalestaxrefListid       sql.NullString
	ItemsalestaxrefFullname     sql.NullString
	Salestaxpercentage          sql.NullString
	Salestaxtotal               sql.NullString
	Appliedamount               sql.NullString
	Balanceremaining            sql.NullString
	CurrencyrefListid           sql.NullString
	CurrencyrefFullname         sql.NullString
	Exchangerate                sql.NullString
	Balremaininginhomecurrency  sql.NullString
	Memo                        sql.NullString
	Ispaid                      sql.NullString
	CustomermsgrefListid        sql.NullString
	CustomermsgrefFullname      sql.NullString
	Istobeprinted               sql.NullString
	Istobeemailed               sql.NullString
	Istaxincluded               sql.NullString
	CustsalestaxcoderefListid   sql.NullString
	CustsalestaxcoderefFullname sql.NullString
	Suggesteddiscountamount     sql.NullString
	Suggesteddiscountdate       sql.NullTime
	Other                       sql.NullString
	ExternalGuid                sql.NullString
	Customfield1                sql.NullString
	Customfield2                sql.NullString
	CustId                      sql.NullString
	Customfield4                sql.NullString
	Customfield5                sql.NullString
	Customfield6                sql.NullString
	Customfield7                sql.NullString
	Customfield8                sql.NullString
	Customfield9                sql.NullString
	Customfield10               sql.NullString
	Customfield11               sql.NullString
	Customfield12               sql.NullString
	Customfield13               sql.NullString
	Customfield14               sql.NullString
	Customfield15               sql.NullString
	Lsdata                      sql.NullString
	Operation                   sql.NullString
	UserData                    sql.NullString
}

type KciQbInvoicelineret struct {
	Txnlineid                 sql.NullString
	ItemRefListId             sql.NullString
	ItemrefFullname           sql.NullString
	Description               sql.NullString
	Quantity                  sql.NullString
	Unitofmeasure             sql.NullString
	OverrideuomsetrefListid   sql.NullString
	OverrideuomsetrefFullname sql.NullString
	Rate                      sql.NullString
	Ratepercent               sql.NullString
	ClassrefListid            sql.NullString
	ClassrefFullname          sql.NullString
	Amount                    sql.NullString
	Taxamount                 sql.NullString
	InvsiterefListid          sql.NullString
	InvsiterefFullname        sql.NullString
	InvsitelocrefListid       sql.NullString
	InvsitelocrefFullname     sql.NullString
	Serialnumber              sql.NullString
	Lotnumber                 sql.NullString
	Servicedate               sql.NullTime
	SalestaxcoderefListid     sql.NullString
	SalestaxcoderefFullname   sql.NullString
	Istaxable                 sql.NullString
	Other1                    sql.NullString
	Other2                    sql.NullString
	LinktotxnTxnid            sql.NullString
	LinktotxnTxnlineid        sql.NullString
	Customfield1              sql.NullString
	Customfield2              sql.NullString
	CustId                    sql.NullString
	Customfield4              sql.NullString
	Customfield5              sql.NullString
	Customfield6              sql.NullString
	Customfield7              sql.NullString
	Customfield8              sql.NullString
	Customfield9              sql.NullString
	Customfield10             sql.NullString
	Customfield11             sql.NullString
	Customfield12             sql.NullString
	Customfield13             sql.NullString
	Customfield14             sql.NullString
	Customfield15             sql.NullString
	ParentIdKey               sql.NullString
	GroupparentIdkey          sql.NullString
	SeqNum                    sql.NullInt32
	Lsdata                    sql.NullString
}

type KciQbReceivepayment struct {
	TxnId                       string
	Timecreated                 sql.NullTime
	Timemodified                sql.NullTime
	Editsequence                sql.NullString
	Txnnumber                   sql.NullInt32
	CustomerRefListId           sql.NullString
	CustomerrefFullname         sql.NullString
	AraccountrefListid          sql.NullString
	AraccountrefFullname        sql.NullString
	Txndate                     sql.NullTime
	Refnumber                   sql.NullString
	Totalamount                 sql.NullString
	PaymentmethodrefListid      sql.NullString
	PaymentmethodrefFullname    sql.NullString
	Memo                        sql.NullString
	DeposittoaccountrefListid   sql.NullString
	DeposittoaccountrefFullname sql.NullString
	Unusedpayment               sql.NullString
	Unusedcredits               sql.NullString
	Lsdata                      sql.NullString
	Operation                   sql.NullString
	UserData                    sql.NullString
}
