// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"time"
)

type Activity struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Category struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Link struct {
	ID           int64          `json:"id"`
	Url          string         `json:"url"`
	Title        sql.NullString `json:"title"`
	Content      sql.NullString `json:"content"`
	Summary      sql.NullString `json:"summary"`
	Status       string         `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	FetchedAt    sql.NullTime   `json:"fetched_at"`
	SummarizedAt sql.NullTime   `json:"summarized_at"`
}

type LinkActivity struct {
	LinkID     int64     `json:"link_id"`
	ActivityID int64     `json:"activity_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type LinkCategory struct {
	LinkID     int64     `json:"link_id"`
	CategoryID int64     `json:"category_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type LinkTag struct {
	LinkID    int64     `json:"link_id"`
	TagID     int64     `json:"tag_id"`
	CreatedAt time.Time `json:"created_at"`
}

type LinkTask struct {
	LinkID    int64     `json:"link_id"`
	TaskID    int64     `json:"task_id"`
	CreatedAt time.Time `json:"created_at"`
}

type LinksFt struct {
	Url     string `json:"url"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Summary string `json:"summary"`
}

type Tag struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Task struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Completed   bool           `json:"completed"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}
