// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package models

import (
	"context"
	"database/sql"
)

const completeTask = `-- name: CompleteTask :exec
UPDATE tasks
SET completed = 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) CompleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeTask, id)
	return err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, description)
VALUES (?, ?)
RETURNING id, name, description, created_at
`

type CreateCategoryParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.Description)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO links (url, title, content, summary, status)
VALUES (?, ?, ?, ?, ?)
RETURNING id, url, title, content, summary, status, created_at, updated_at, fetched_at, summarized_at
`

type CreateLinkParams struct {
	Url     string         `json:"url"`
	Title   sql.NullString `json:"title"`
	Content sql.NullString `json:"content"`
	Summary sql.NullString `json:"summary"`
	Status  string         `json:"status"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, createLink,
		arg.Url,
		arg.Title,
		arg.Content,
		arg.Summary,
		arg.Status,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FetchedAt,
		&i.SummarizedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name)
VALUES (?)
RETURNING id, name, created_at
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (name, description)
VALUES (?, ?)
RETURNING id, name, description, completed, created_at, updated_at
`

type CreateTaskParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.Name, arg.Description)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM links
WHERE id = ?
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLink, id)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getCategoriesForLink = `-- name: GetCategoriesForLink :many
SELECT c.id, c.name, c.description, c.created_at FROM categories c
JOIN link_categories lc ON c.id = lc.category_id
WHERE lc.link_id = ?
ORDER BY c.name
`

func (q *Queries) GetCategoriesForLink(ctx context.Context, linkID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesForLink, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, description, created_at FROM categories
WHERE id = ?
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getLink = `-- name: GetLink :one
SELECT id, url, title, content, summary, status, created_at, updated_at, fetched_at, summarized_at FROM links
WHERE id = ?
`

func (q *Queries) GetLink(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FetchedAt,
		&i.SummarizedAt,
	)
	return i, err
}

const getLinkByURL = `-- name: GetLinkByURL :one
SELECT id, url, title, content, summary, status, created_at, updated_at, fetched_at, summarized_at FROM links
WHERE url = ?
`

func (q *Queries) GetLinkByURL(ctx context.Context, url string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByURL, url)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FetchedAt,
		&i.SummarizedAt,
	)
	return i, err
}

const getLinksForCategory = `-- name: GetLinksForCategory :many
SELECT l.id, l.url, l.title, l.content, l.summary, l.status, l.created_at, l.updated_at, l.fetched_at, l.summarized_at FROM links l
JOIN link_categories lc ON l.id = lc.link_id
WHERE lc.category_id = ?
ORDER BY l.created_at DESC
`

func (q *Queries) GetLinksForCategory(ctx context.Context, categoryID int64) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, getLinksForCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FetchedAt,
			&i.SummarizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinksForTag = `-- name: GetLinksForTag :many
SELECT l.id, l.url, l.title, l.content, l.summary, l.status, l.created_at, l.updated_at, l.fetched_at, l.summarized_at FROM links l
JOIN link_tags lt ON l.id = lt.link_id
WHERE lt.tag_id = ?
ORDER BY l.created_at DESC
`

func (q *Queries) GetLinksForTag(ctx context.Context, tagID int64) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, getLinksForTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FetchedAt,
			&i.SummarizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinksForTask = `-- name: GetLinksForTask :many
SELECT l.id, l.url, l.title, l.content, l.summary, l.status, l.created_at, l.updated_at, l.fetched_at, l.summarized_at FROM links l
JOIN link_tasks lt ON l.id = lt.link_id
WHERE lt.task_id = ?
ORDER BY l.created_at DESC
`

func (q *Queries) GetLinksForTask(ctx context.Context, taskID int64) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, getLinksForTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FetchedAt,
			&i.SummarizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTag = `-- name: GetTag :one
SELECT id, name, created_at FROM tags
WHERE id = ?
`

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, created_at FROM tags
WHERE name = ?
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTagsForLink = `-- name: GetTagsForLink :many
SELECT t.id, t.name, t.created_at FROM tags t
JOIN link_tags lt ON t.id = lt.tag_id
WHERE lt.link_id = ?
ORDER BY t.name
`

func (q *Queries) GetTagsForLink(ctx context.Context, linkID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForLink, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, name, description, completed, created_at, updated_at FROM tasks
WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTasksForLink = `-- name: GetTasksForLink :many
SELECT t.id, t.name, t.description, t.completed, t.created_at, t.updated_at FROM tasks t
JOIN link_tasks lt ON t.id = lt.task_id
WHERE lt.link_id = ?
ORDER BY t.created_at DESC
`

func (q *Queries) GetTasksForLink(ctx context.Context, linkID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksForLink, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkCategory = `-- name: LinkCategory :exec
INSERT INTO link_categories (link_id, category_id)
VALUES (?, ?)
`

type LinkCategoryParams struct {
	LinkID     int64 `json:"link_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) LinkCategory(ctx context.Context, arg LinkCategoryParams) error {
	_, err := q.db.ExecContext(ctx, linkCategory, arg.LinkID, arg.CategoryID)
	return err
}

const linkTag = `-- name: LinkTag :exec
INSERT INTO link_tags (link_id, tag_id)
VALUES (?, ?)
`

type LinkTagParams struct {
	LinkID int64 `json:"link_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) LinkTag(ctx context.Context, arg LinkTagParams) error {
	_, err := q.db.ExecContext(ctx, linkTag, arg.LinkID, arg.TagID)
	return err
}

const linkTask = `-- name: LinkTask :exec
INSERT INTO link_tasks (link_id, task_id)
VALUES (?, ?)
`

type LinkTaskParams struct {
	LinkID int64 `json:"link_id"`
	TaskID int64 `json:"task_id"`
}

func (q *Queries) LinkTask(ctx context.Context, arg LinkTaskParams) error {
	_, err := q.db.ExecContext(ctx, linkTask, arg.LinkID, arg.TaskID)
	return err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, description, created_at FROM categories
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncompleteTasks = `-- name: ListIncompleteTasks :many
SELECT id, name, description, completed, created_at, updated_at FROM tasks
WHERE completed = 0
ORDER BY created_at DESC
`

func (q *Queries) ListIncompleteTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listIncompleteTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinks = `-- name: ListLinks :many
SELECT id, url, title, content, summary, status, created_at, updated_at, fetched_at, summarized_at FROM links
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListLinksParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listLinks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FetchedAt,
			&i.SummarizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksByStatus = `-- name: ListLinksByStatus :many
SELECT id, url, title, content, summary, status, created_at, updated_at, fetched_at, summarized_at FROM links
WHERE status = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListLinksByStatusParams struct {
	Status string `json:"status"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListLinksByStatus(ctx context.Context, arg ListLinksByStatusParams) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listLinksByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FetchedAt,
			&i.SummarizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, created_at FROM tags
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, name, description, completed, created_at, updated_at FROM tasks
ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLinks = `-- name: SearchLinks :many
SELECT id, url, title, content, summary, status, created_at, updated_at, fetched_at, summarized_at FROM links
WHERE 
    url LIKE ? OR
    title LIKE ? OR
    content LIKE ? OR
    summary LIKE ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type SearchLinksParams struct {
	Url     string         `json:"url"`
	Title   sql.NullString `json:"title"`
	Content sql.NullString `json:"content"`
	Summary sql.NullString `json:"summary"`
	Limit   int64          `json:"limit"`
	Offset  int64          `json:"offset"`
}

func (q *Queries) SearchLinks(ctx context.Context, arg SearchLinksParams) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, searchLinks,
		arg.Url,
		arg.Title,
		arg.Content,
		arg.Summary,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FetchedAt,
			&i.SummarizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkCategory = `-- name: UnlinkCategory :exec
DELETE FROM link_categories
WHERE link_id = ? AND category_id = ?
`

type UnlinkCategoryParams struct {
	LinkID     int64 `json:"link_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) UnlinkCategory(ctx context.Context, arg UnlinkCategoryParams) error {
	_, err := q.db.ExecContext(ctx, unlinkCategory, arg.LinkID, arg.CategoryID)
	return err
}

const unlinkTag = `-- name: UnlinkTag :exec
DELETE FROM link_tags
WHERE link_id = ? AND tag_id = ?
`

type UnlinkTagParams struct {
	LinkID int64 `json:"link_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) UnlinkTag(ctx context.Context, arg UnlinkTagParams) error {
	_, err := q.db.ExecContext(ctx, unlinkTag, arg.LinkID, arg.TagID)
	return err
}

const unlinkTask = `-- name: UnlinkTask :exec
DELETE FROM link_tasks
WHERE link_id = ? AND task_id = ?
`

type UnlinkTaskParams struct {
	LinkID int64 `json:"link_id"`
	TaskID int64 `json:"task_id"`
}

func (q *Queries) UnlinkTask(ctx context.Context, arg UnlinkTaskParams) error {
	_, err := q.db.ExecContext(ctx, unlinkTask, arg.LinkID, arg.TaskID)
	return err
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET title = ?,
    content = ?,
    summary = ?,
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, url, title, content, summary, status, created_at, updated_at, fetched_at, summarized_at
`

type UpdateLinkParams struct {
	Title   sql.NullString `json:"title"`
	Content sql.NullString `json:"content"`
	Summary sql.NullString `json:"summary"`
	Status  string         `json:"status"`
	ID      int64          `json:"id"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, updateLink,
		arg.Title,
		arg.Content,
		arg.Summary,
		arg.Status,
		arg.ID,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FetchedAt,
		&i.SummarizedAt,
	)
	return i, err
}

const updateLinkFetchedAt = `-- name: UpdateLinkFetchedAt :exec
UPDATE links
SET fetched_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateLinkFetchedAt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateLinkFetchedAt, id)
	return err
}

const updateLinkSummarizedAt = `-- name: UpdateLinkSummarizedAt :exec
UPDATE links
SET summarized_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateLinkSummarizedAt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateLinkSummarizedAt, id)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET name = ?,
    description = ?,
    completed = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, description, completed, created_at, updated_at
`

type UpdateTaskParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Completed   bool           `json:"completed"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Name,
		arg.Description,
		arg.Completed,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
